GL_INCLUDE = /usr/X11R6/include
GL_LIB = /usr/X11R6/lib

CC = gcc
CFLAGS = -g $(GL_INCLUDE)
LIBS = -lGL -lglut -lGLEW -lm

triangle: triangle.o
	$(CC) -o triangle $^ -L$(GL_LIB) triangle.c $(LIBS)

.c.o:
    $(CC) -c -o $@ $< -I$(GL_INCLUDE)

clean:
    rm -f triangle.o

