GL_INCLUDE = /usr/X11R6/include
GL_LIB = /usr/X11R6/lib

CC = gcc
CFLAGS = -g $(GL_INCLUDE)
LIBS = -lGL -lglut -lGLEW -lm

triangle: triangle.o
	$(CC) $(CFLAGS) -o triangle $(LIBDIRS) triangle.c $(LIBS)

